parameters:
#    acme_ged.example.class: Acme\GedBundle\Example

services:
#    acme_ged.example:
#        class: %acme_ged.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
