Mevia\GedBundle\Entity\User:
    type: entity
    table: users
    uniqueConstraints:
        email_uk:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: first_name
        lastName:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: last_name
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        createdAt:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: updated_at
    lifecycleCallbacks: {  }
