mevia_ged_homepage:
    pattern: /
    defaults: { _controller: MeviaGedBundle:Default:index }

mevia_ged_login:
    pattern: /login
    defaults: { _controller: MeviaGedBundle:Default:login }

mevia_ged_logout:
    pattern: /logout
    defaults: { _controller: MeviaGedBundle:Default:logout }

mevia_ged_dashboard:
    pattern: /dashboard
    defaults: { _controller: MeviaGedBundle:Default:dashboard }
