parameters:
#    mevia_ged.example.class: Mevia\GedBundle\Example

services:
#    mevia_ged.example:
#        class: %mevia_ged.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
